/**
 * apk.js — Android APK builder via GitHub Actions
 *
 * Works on any machine (including Termux on Android) because the heavy
 * Gradle / Android SDK work happens in a GitHub Actions runner, not locally.
 *
 * Flow:
 *   1. Push a build-apk workflow to the target repo via GitHub API
 *   2. Trigger workflow_dispatch
 *   3. Poll the Actions API until the run completes
 *   4. Download the APK artifact zip and extract the .apk
 *   5. Serve it for download
 *
 * Token requirement: the existing DeployView GitHub token needs the
 * "workflow" scope in addition to "repo". Re-paste your token in Settings
 * with that scope if APK builds fail at the "push workflow" step.
 */

const https  = require("https");
const http   = require("http");
const fs     = require("fs");
const path   = require("path");
const { execFile } = require("child_process");

const { getConfig }  = require("./config");
const { buildStatus, WORKSPACE } = require("./build");
const { broadcastLog } = require("./logs");

const APK_DIR = path.join(WORKSPACE, ".apks");
if (!fs.existsSync(APK_DIR)) fs.mkdirSync(APK_DIR, { recursive: true });

// key → { status, log, apkPath, sizeKb, startedAt, runUrl }
const apkStatus = {};

// ─── tiny GitHub REST helper ──────────────────────────────────────────────────

function ghReq(method, endpoint, body, token) {
  return new Promise((resolve, reject) => {
    const data = body ? JSON.stringify(body) : null;
    const req  = https.request({
      hostname: "api.github.com",
      path: endpoint,
      method,
      headers: {
        "User-Agent":           "deployview-apk/1.0",
        "Authorization":        "Bearer " + token,
        "Accept":               "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        ...(data ? { "Content-Type": "application/json", "Content-Length": Buffer.byteLength(data) } : {})
      }
    }, res => {
      let buf = "";
      res.on("data", d => { buf += d; });
      res.on("end", () => {
        if (res.statusCode === 204) return resolve({});
        if (res.statusCode >= 400) return reject(new Error("GitHub " + res.statusCode + " " + method + " " + endpoint + ": " + buf.slice(0, 300)));
        try { resolve(buf ? JSON.parse(buf) : {}); } catch (e) { resolve(buf); }
      });
    });
    req.on("error", reject);
    if (data) req.write(data);
    req.end();
  });
}

// Follow redirects and save binary to disk
function downloadFile(url, dest, token) {
  return new Promise((resolve, reject) => {
    function follow(u) {
      const mod = u.startsWith("https") ? https : http;
      const opts = new URL(u);
      mod.get({ hostname: opts.hostname, path: opts.pathname + opts.search, headers: {
        "User-Agent":    "deployview-apk/1.0",
        "Authorization": "Bearer " + token,
        "Accept":        "application/vnd.github+json"
      }}, res => {
        if (res.statusCode === 301 || res.statusCode === 302) return follow(res.headers.location);
        if (res.statusCode !== 200) return reject(new Error("Download " + res.statusCode + " from " + u));
        const out = fs.createWriteStream(dest);
        res.pipe(out);
        out.on("finish", () => out.close(resolve));
        out.on("error", reject);
      }).on("error", reject);
    }
    follow(url);
  });
}

// ─── workflow YAML ────────────────────────────────────────────────────────────

function makeWorkflow(appId, appName, buildCommand, outputDir, workingDir) {
  // Normalise: blank / "." / "./" all mean repo root
  const wd = (workingDir || ".").replace(/\/$/, "") || ".";
  const isRoot = (wd === ".");

  // YAML single-quote escape: a single quote inside a single-quoted
  // YAML string is doubled. Without this, a buildCommand containing
  // a single quote (e.g. `node -e "console.log('hi')"`) would close
  // the string early and produce invalid YAML — the generated
  // workflow would fail to parse and the APK build would die at
  // GitHub Actions parse time with a confusing error.
  function yq(s) { return "'" + String(s).replace(/'/g, "''") + "'"; }

  return [
    "# Auto-generated by DeployView — safe to delete after use",
    "name: DeployView APK Build",
    "",
    "on:",
    "  workflow_dispatch:",
    "    inputs:",
    "      build_command:",
    "        description: Web build command",
    "        default: " + yq(buildCommand || "npm run build"),
    "      output_dir:",
    "        description: Web output directory",
    "        default: " + yq(outputDir || "dist"),
    "      working_directory:",
    "        description: Subdirectory containing package.json (leave blank for repo root)",
    "        default: " + yq(wd),
    "",
    "jobs:",
    "  build-apk:",
    "    runs-on: ubuntu-latest",
    "    defaults:",
    "      run:",
    "        working-directory: ${{ github.event.inputs.working_directory }}",
    "    steps:",
    "      - uses: actions/checkout@v4",
    "",
    "      - uses: actions/setup-node@v4",
    "        with:",
    "          node-version: '20'",
    "",
    "      - uses: actions/setup-java@v4",
    "        with:",
    "          distribution: temurin",
    "          java-version: '17'",
    "",
    "      - uses: android-actions/setup-android@v3",
    "",
    "      - name: Install web dependencies",
    "        run: npm install",
    "",
    "      - name: Build web app",
    "        run: ${{ github.event.inputs.build_command }}",
    "",
    "      - name: Install Capacitor",
    "        run: npm install --save @capacitor/core @capacitor/cli @capacitor/android",
    "",
    "      - name: Write capacitor config",
    "        run: |",
    "          cat > capacitor.config.json <<'EOF'",
    '          {"appId":"' + appId + '","appName":"' + appName + '","webDir":"${{ github.event.inputs.output_dir }}","bundledWebRuntime":false}',
    "          EOF",
    "",
    "      - name: Add Android & sync",
    "        run: |",
    "          npx cap add android",
    "          npx cap sync android",
    "",
    "      - name: Build debug APK",
    "        run: |",
    "          cd android && chmod +x gradlew && ./gradlew assembleDebug --no-daemon",
    "",
    "      - uses: actions/upload-artifact@v4",
    "        with:",
    "          name: deployview-apk",
    "          path: ${{ github.event.inputs.working_directory }}/android/app/build/outputs/apk/debug/app-debug.apk",
    "          retention-days: 7",
    ""
  ].join("\n");
}

// Native Android/Kotlin project: build the repo's own Gradle project
// directly — no web build, no Capacitor wrapper.
function makeNativeAndroidWorkflow(workingDir) {
  const wd = (workingDir || ".").replace(/\/$/, "") || ".";
  function yq(s) { return "'" + String(s).replace(/'/g, "''") + "'"; }

  return [
    "# Auto-generated by DeployView — safe to delete after use",
    "name: DeployView Native Android APK Build",
    "",
    "on:",
    "  workflow_dispatch:",
    "    inputs:",
    "      working_directory:",
    "        description: Subdirectory containing settings.gradle (leave blank for repo root)",
    "        default: " + yq(wd),
    "",
    "jobs:",
    "  build-apk:",
    "    runs-on: ubuntu-latest",
    "    defaults:",
    "      run:",
    "        working-directory: ${{ github.event.inputs.working_directory }}",
    "    steps:",
    "      - uses: actions/checkout@v4",
    "",
    "      - uses: actions/setup-java@v4",
    "        with:",
    "          distribution: temurin",
    "          java-version: '17'",
    "",
    "      - uses: android-actions/setup-android@v3",
    "",
    "      - name: Build debug APK",
    "        run: |",
    "          chmod +x gradlew",
    "          ./gradlew assembleDebug --no-daemon",
    "",
    "      - name: Find APK",
    "        id: findapk",
    "        run: echo \"path=$(find \\\"$(pwd)\\\" -path '*/outputs/apk/debug/*.apk' | head -n1)\" >> $GITHUB_OUTPUT",
    "",
    "      - uses: actions/upload-artifact@v4",
    "        with:",
    "          name: deployview-apk",
    "          path: ${{ steps.findapk.outputs.path }}",
    "          retention-days: 7",
    ""
  ].join("\n");
}

// ─── logging ──────────────────────────────────────────────────────────────────

function addLog(key, msg) {
  if (!apkStatus[key]) return;
  apkStatus[key].log += msg + "\n";
  broadcastLog("apk:" + key, msg);
  console.log("[APK:" + key + "] " + msg);
}

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

// ─── main ─────────────────────────────────────────────────────────────────────

async function buildApk(owner, repo, slug, workingDir) {
  const key   = owner + "/" + repo + ":" + slug;
  const bs    = buildStatus[key];
  const token = getConfig().token;

  apkStatus[key] = { status: "building", log: "", apkPath: null, startedAt: Date.now(), runUrl: null };

  // ── guards ───────────────────────────────────────────────────────────────
  if (!token) {
    addLog(key, "ERROR: No GitHub token. Add one in the DeployView settings first.");
    apkStatus[key].status = "error"; return;
  }
  if (!bs || (bs.status !== "ready" && bs.status !== "running")) {
    addLog(key, "ERROR: Deploy this branch successfully before building an APK.");
    apkStatus[key].status = "error"; return;
  }

  const isNative   = !!bs.isNativeAndroid;
  const buildCmd   = bs.buildCommand || "npm run build";
  const outputDir  = bs.outputDir    || "dist";
  const workDir    = (workingDir || bs.workingDir || ".").replace(/\/$/, "") || ".";
  const appName   = repo.replace(/[^a-zA-Z0-9]/g, "") || "App";
  const appId     = "com.deployview." +
                    owner.replace(/[^a-zA-Z0-9]/g, "").toLowerCase() + "." +
                    repo.replace(/[^a-zA-Z0-9]/g, "").toLowerCase();

  const WORKFLOW_FILE = ".github/workflows/deployview-apk.yml";

  // ── 1. get default branch ────────────────────────────────────────────────
  addLog(key, "Fetching repo info...");
  let defaultBranch;
  try {
    const info = await ghReq("GET", "/repos/" + owner + "/" + repo, null, token);
    defaultBranch = info.default_branch || "main";
    addLog(key, "Default branch: " + defaultBranch);
  } catch (e) {
    addLog(key, "ERROR: " + e.message); apkStatus[key].status = "error"; return;
  }

  // ── 2. upsert workflow file (idempotent — F-A015) ────────────────────────
  // Don't pollute the user's git history with no-op commits when nothing
  // has changed. Compare the existing file's contents byte-for-byte first.
  addLog(key, "Checking build workflow in repo...");
  const newContent = isNative ? makeNativeAndroidWorkflow(workDir) : makeWorkflow(appId, appName, buildCmd, outputDir, workDir);
  const newContentB64 = Buffer.from(newContent).toString("base64");
  let existingSha = null, existingContent = "";
  try {
    const f = await ghReq("GET", "/repos/" + owner + "/" + repo + "/contents/" + WORKFLOW_FILE + "?ref=" + defaultBranch, null, token);
    existingSha = f.sha;
    if (f.content) existingContent = Buffer.from(f.content, "base64").toString("utf8");
  } catch (e) { /* new file */ }

  if (existingContent === newContent) {
    addLog(key, "Workflow already up-to-date — skipping commit.");
  } else {
    try {
      await ghReq("PUT", "/repos/" + owner + "/" + repo + "/contents/" + WORKFLOW_FILE, {
        message: "chore: DeployView APK workflow [skip ci]",
        content: newContentB64,
        branch: defaultBranch,
        ...(existingSha ? { sha: existingSha } : {})
      }, token);
      addLog(key, existingSha ? "Workflow updated." : "Workflow file added.");
    } catch (e) {
      addLog(key, "ERROR pushing workflow: " + e.message);
      addLog(key, "Tip: re-save your GitHub token with the 'workflow' scope enabled. If main is branch-protected, the token must also have permission to push to it (or use a fine-grained PAT scoped to this repo).");
      apkStatus[key].status = "error"; return;
    }
  }

  await sleep(4000); // let GitHub register the workflow

  // ── 3. trigger workflow_dispatch ─────────────────────────────────────────
  addLog(key, "Triggering GitHub Actions run...");
  const triggerTime = Date.now();
  try {
    await ghReq("POST", "/repos/" + owner + "/" + repo + "/actions/workflows/deployview-apk.yml/dispatches", {
      ref: defaultBranch,
      inputs: isNative
        ? { working_directory: workDir }
        : { build_command: buildCmd, output_dir: outputDir, working_directory: workDir }
    }, token);
  } catch (e) {
    addLog(key, "ERROR triggering workflow: " + e.message);
    apkStatus[key].status = "error"; return;
  }

  // ── 4. find run ID ───────────────────────────────────────────────────────
  addLog(key, "Waiting for run to appear in Actions...");
  let runId = null, runUrl = null;
  for (let i = 0; i < 24; i++) {
    await sleep(5000);
    try {
      const runs = await ghReq("GET", "/repos/" + owner + "/" + repo + "/actions/workflows/deployview-apk.yml/runs?per_page=5", null, token);
      for (const r of (runs.workflow_runs || [])) {
        if (new Date(r.created_at).getTime() >= triggerTime - 60000) {
          runId = r.id; runUrl = r.html_url; break;
        }
      }
    } catch (e) { /* retry */ }
    if (runId) break;
    addLog(key, "  still waiting... " + Math.round((i + 1) * 5) + "s");
  }
  if (!runId) {
    addLog(key, "ERROR: Run did not appear after 2 minutes. Check " +
      "https://github.com/" + owner + "/" + repo + "/actions");
    apkStatus[key].status = "error"; return;
  }
  apkStatus[key].runUrl = runUrl;
  addLog(key, "Run started → " + runUrl);

  // ── 5. poll until complete ───────────────────────────────────────────────
  addLog(key, "Building in the cloud (usually 4–8 min)...");
  let conclusion = null;
  for (let i = 0; i < 120; i++) {
    await sleep(10000);
    try {
      const run  = await ghReq("GET", "/repos/" + owner + "/" + repo + "/actions/runs/" + runId, null, token);
      conclusion = run.conclusion;
      const elapsed = Math.round((Date.now() - triggerTime) / 60000);
      addLog(key, "  " + run.status + (conclusion ? " → " + conclusion : "") + " (" + elapsed + "min)");
      if (run.status === "completed") break;
    } catch (e) { addLog(key, "  poll error: " + e.message); }
  }
  if (conclusion !== "success") {
    addLog(key, "ERROR: Build " + (conclusion || "timed out") + ". Details: " + runUrl);
    apkStatus[key].status = "error"; return;
  }

  // ── 6. download artifact ─────────────────────────────────────────────────
  addLog(key, "Downloading APK artifact...");
  let artifactId = null;
  try {
    const art = await ghReq("GET", "/repos/" + owner + "/" + repo + "/actions/runs/" + runId + "/artifacts", null, token);
    const found = (art.artifacts || []).find(a => a.name === "deployview-apk");
    if (!found) throw new Error("Artifact 'deployview-apk' not in run " + runId);
    artifactId = found.id;
  } catch (e) {
    addLog(key, "ERROR: " + e.message); apkStatus[key].status = "error"; return;
  }

  const safeSlug  = (owner + "_" + repo + "_" + slug).replace(/[^a-zA-Z0-9_-]/g, "_");
  const zipPath   = path.join(APK_DIR, safeSlug + "_art.zip");
  const extractTo = path.join(APK_DIR, safeSlug + "_extracted");
  const apkDest   = path.join(APK_DIR, safeSlug + ".apk");

  // Validate all paths stay inside APK_DIR
  const resolvedDir = path.resolve(APK_DIR) + path.sep;
  if (![zipPath, extractTo, apkDest].every(p => path.resolve(p).startsWith(resolvedDir))) {
    addLog(key, "ERROR: Invalid path generated"); apkStatus[key].status = "error"; return;
  }

  try {
    const dlUrl = "https://api.github.com/repos/" + owner + "/" + repo + "/actions/artifacts/" + artifactId + "/zip";
    await downloadFile(dlUrl, zipPath, token);
    addLog(key, "Artifact downloaded. Extracting...");
    if (fs.existsSync(extractTo)) fs.rmSync(extractTo, { recursive: true, force: true });
    fs.mkdirSync(extractTo, { recursive: true });
    await new Promise((resolve, reject) => {
      execFile("unzip", ["-o", zipPath, "-d", extractTo], (err) => err ? reject(err) : resolve());
    });
    const files  = fs.readdirSync(extractTo);
    const apkFile = files.find(f => f.endsWith(".apk"));
    if (!apkFile) throw new Error("No .apk in artifact. Contents: " + files.join(", "));
    fs.copyFileSync(path.join(extractTo, apkFile), apkDest);
    fs.unlinkSync(zipPath);
    fs.rmSync(extractTo, { recursive: true, force: true });
  } catch (e) {
    addLog(key, "ERROR extracting artifact: " + e.message);
    apkStatus[key].status = "error"; return;
  }

  const sizeKb = Math.round(fs.statSync(apkDest).size / 1024);
  addLog(key, "✓ APK ready! " + sizeKb + " KB");
  apkStatus[key].status  = "ready";
  apkStatus[key].apkPath = apkDest;
  apkStatus[key].sizeKb  = sizeKb;
}

module.exports = { apkStatus, buildApk, APK_DIR };
